### ISSUE TITLE
Maybe: restore IE support by using extendNew (instead of Object.assign)

### ISSUE THREAD

**Issue by issa-tseng** [issa-tseng/janus#119]
Would rather not do this, but willing to revert the change if people need/want this. Consider this issue a ticket to vote on it.

**Comment by clint-tseng** [comment]
Now with the addition of Navigator there is some code that presumes the existence of `Symbol` as well.

**Comment by issa-tseng** [comment]
oops, we also use `String#startsWith`

**Comment by issa-tseng** [comment]
we are modernizing. this is not gonna happen.
