### ISSUE TITLE
Add attribute.Model.ofRecursive and attribute.List.ofRecursive

### ISSUE THREAD

**Issue by issa-tseng** [issa-tseng/janus#134]
these constructs are annoying to synthesize today.

**Comment by clint-tseng** [comment]
probably as part of this make the `@modelClass` and `@listClass` properties not class properties.

**Comment by issa-tseng** [comment]
we would have to special case this into the Model builder to make this work, since the same reason these constructs are annoying also prevents us directly solving the problem (eg @deserialize is resolved bottom-up)
