### ISSUE TITLE
jQuery-like navigation of the DomView hierarchy

### ISSUE THREAD

**Issue by issa-tseng** [issa-tseng/janus#137]
as an example, look at the repl in janus-docs (abridged):

``` javascript
class ReplView extends DomView.build($(/* some html */), template(
  find('.repl-main').render(from('statements'))
    .options(from.self().map((view) => ({
      renderItem: (render) => render.options({ onCommit: () => { view.commit(); } })
    }))),
  find('.repl-main')
    .on('click', (event, _, view) => {
      if (event.target === view.artifact().find('.repl-main')[0])
        view.focusLast();
    }) /*, other bindings */
)) {
  commit() {
    this.subject.commit();
    this.focusLast();
  }
  focusLast() {
    // TODO: still feels like a hack.
    const lastEditorView = this.artifact().find('.repl-main > ul > li:last-child .code-editor').data('view');
    lastEditorView.focus();
  }
}
```

1. it feels annoying that we have to _push_ the `onCommit` handler down to children. consider alternatively how we use `_initialize` to set up simple "if this data change then do this operation" reactions just based on the data.
2. it's definitely awful that from this solid View object, we have to navigate through the _DOM tree_ of all things to find a View object two levels deep.

not illustrated here are similar annoyances around getting eg parent `List`s to do things like reference their length or check the following sibling. there was a time when janus provided some sort of view stack concept via `app` but this has been abandoned as a sledgehammer solution to a fine plumbing problem (mostly because it necessitates an `app.shadow()` at _every_ View instantiation, which interferes with app authors' ability to manage app state).

instead, one might imagine some kind of DomView interface by which the View objects corresponding with given View subjects (typically Models) might be retrieved.

something (very very roughly) like this:

``` javascript
focusLast() {
  this.into('statements').into(statements => statements.get_(-1));
  // alternatively, List in particular could perhaps provide this shortcut:
  this.into('statements').into(-1);
}
```

``` javascript
find('.editor').on('commit', (e, s, view) => { view.closest(Repl).forEach(repl => { repl.commit(); }) })
```

we for sure for sure don't want to build all of jQuery. i think we can get away with:

* `.into(x)` which navigates down the tree
* `.closest(x)` which navigates up the tree (but how?)

where `x` can be a classtype, a specific instance, a string/int which will be passed to `subject.get(x)`, or a function which given the `subject` returns one of the aforementioned values.

possibly `parent` and/or `parents`.

**Comment by clint-tseng** [comment]
this ticket mostly subsumes #78.

the only way in which it doesn't is that this ticket only addresses the view hierarchy, and not model objects. but the view hierarchy presents this problem far more frequently in practical scenarios, so it is the major concern.
